// ui/src/constants.ts
// Recreating responsesText and VERSION as they were in the original project.

export const ruleTranslations: { [key: string]: string } = {
  required: 'Obrigatório',
  string: 'Texto',
  integer: 'Integer',
  numeric: 'Numeric',
  array: 'Array',
  boolean: 'Boolean',
  email: 'Email',
  uuid: 'UUID',
  nullable: 'Optional',
  min: 'Min',
  max: 'Max',
  confirmed: 'Confirmed',
  unique: 'Unique',
  exists: 'Exists in DB',
  date: 'Date',
  file: 'File',
  image: 'Image',
  in: 'In',
  regex: 'Pattern',
  bail: 'Stop on first failure',
  prohibited_unless: 'Proibido, a menos que',
  // Add more as needed
};

export const responsesText: { [key: string]: string } = {
  "100": "Continue",
  "101": "Switching Protocols",
  "102": "Processing",
  "103": "Early Hints",
  "200": "OK",
  "201": "Created",
  "202": "Accepted",
  "203": "Non-Authoritative Information",
  "204": "No Content",
  "205": "Reset Content",
  "206": "Partial Content",
  "207": "Multi-Status",
  "208": "Already Reported",
  "226": "IM Used",
  "300": "Multiple Choices",
  "301": "Moved Permanently",
  "302": "Found",
  "303": "See Other",
  "304": "Not Modified",
  "305": "Use Proxy",
  "307": "Temporary Redirect",
  "308": "Permanent Redirect",
  "400": "Bad Request",
  "401": "Unauthorized",
  "402": "Payment Required",
  "403": "Forbidden",
  "404": "Not Found",
  "405": "Method Not Allowed",
  "406": "Not Acceptable",
  "407": "Proxy Authentication Required",
  "408": "Request Timeout",
  "409": "Conflict",
  "410": "Gone",
  "411": "Length Required",
  "412": "Precondition Failed",
  "413": "Payload Too Large",
  "414": "URI Too Long",
  "415": "Unsupported Media Type",
  "416": "Range Not Satisfiable",
  "417": "Expectation Failed",
  "418": "I'm a Teapot",
  "421": "Misdirected Request",
  "422": "Unprocessable Content",
  "423": "Locked",
  "424": "Failed Dependency",
  "425": "Too Early",
  "426": "Upgrade Required",
  "428": "Precondition Required",
  "429": "Too Many Requests",
  "431": "Request Header Fields Too Large",
  "451": "Unavailable For Legal Reasons",
  "500": "Internal Server Error",
  "501": "Not Implemented",
  "502": "Bad Gateway",
  "503": "Service Unavailable",
  "504": "Gateway Timeout",
  "505": "HTTP Version Not Supported",
  "506": "Variant Also Negotiates",
  "507": "Insufficient Storage",
  "508": "Loop Detected",
  "510": "Not Extended",
  "511": "Network Authentication Required",
};

// Placeholder for version, as it's not defined in the new project structure yet.
export const VERSION = "0.0.0";
